---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oawqoqml/public_html/
    - find . -mindepth 1 -maxdepth 1 -exec /bin/cp -R {} "$DEPLOYPATH" \;
    - /bin/rm -rf "$DEPLOYPATH/.git" "$DEPLOYPATH/.cpanel.yml" "$DEPLOYPATH/DOC"
    - find "$DEPLOYPATH" -maxdepth 1 -type f -name "*.txt" -delete
