---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oawqoqml/public_html/
    - /bin/rm -rf "$DEPLOYPATH/DOC"
    - find "$DEPLOYPATH" -maxdepth 1 -type f -name "*.txt" -delete
    - find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".cpanel.yml" -exec /bin/cp -R {} "$DEPLOYPATH" \;
