<?php
$bp = defined('BASE_PATH') ? BASE_PATH : '';
$e = static fn(string $v): string => htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
$nomeCidade = (string)($cidade['nome'] ?? 'sua cidade');
$slugCidade = (string)($cidade['slug'] ?? '');
$url = $bp . '/parceiros/oficinas-' . rawurlencode($slugCidade);
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Oficinas parceiras em <?= $e($nomeCidade) ?> | GuinchaFácil</title>
<meta name="description" content="Demonstre interesse em receber oportunidades qualificadas da GuinchaFácil em <?= $e($nomeCidade) ?>.">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/tokens.css"><link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-landing.css">
<script<?= function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : '' ?> type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'Organization','name'=>'GuinchaFácil','url'=>'https://guinchafacil.com.br/','areaServed'=>['@type'=>'City','name'=>$nomeCidade]], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
</head><body class="gf-landing"><header class="gf-nav"><a class="gf-brand" href="<?= $e($bp) ?>/">Guincha<strong>Fácil</strong></a><nav><a href="<?= $e($bp) ?>/guincho/<?= $e($slugCidade) ?>">Precisa de socorro?</a><a class="gf-login" href="<?= $e($bp) ?>/login">Entrar</a></nav></header>
<main><section class="gf-hero"><div><p class="gf-eyebrow">Rede parceira local</p><h1>Receba oportunidades qualificadas em <em><?= $e($nomeCidade) ?></em></h1><p class="gf-lead">A GuinchaFácil conecta motoristas a guinchos e oficinas parceiras. Envie seu interesse e nossa equipe fará o contato para explicar a operação.</p><?php if ($enviado): ?><div class="gf-trust"><div><b>Interesse recebido</b><span>A equipe responsável pela região avaliará seu contato.</span></div></div><?php endif; ?></div><div class="gf-card"><div class="gf-card-head"><span class="gf-dot"></span><b>Como funciona</b></div><div class="gf-location"><span>1</span><div><small>Você demonstra interesse</small><b>Sem cadastro automático</b></div></div><div class="gf-location"><span>2</span><div><small>A equipe entra em contato</small><b>Operação explicada com clareza</b></div></div><div class="gf-location"><span>3</span><div><small>O admin avalia o parceiro</small><b>Entrada sujeita à aprovação</b></div></div></div></section>
<section class="gf-trust"><div><b>Demanda qualificada</b><span>Receba oportunidades compatíveis com a região.</span></div><div><b>Risco sob controle</b><span>Condições comerciais e operação são explicadas antes da aprovação.</span></div><div><b>Rede local</b><span>O planejamento é organizado por cidade e região.</span></div></section>
<section class="gf-section"><p class="gf-eyebrow">Próximo passo</p><h2>Quer conversar sobre ser parceiro?</h2><p class="gf-muted">Preencha o formulário. Seu contato entra na fila de prospecção da região; isso não cria uma conta nem aprova a oficina automaticamente.</p><?php if ($erro !== ''): ?><p class="gf-muted">Não foi possível registrar o interesse agora. Confira os dados e tente novamente.</p><?php endif; ?><form method="post" action="<?= $e($url) ?>" class="gf-process"><input type="hidden" name="csrf_token" value="<?= $e((string)$csrf_token) ?>"><label>Nome da oficina<input required maxlength="180" name="nome_oficina"></label><label>WhatsApp / telefone<input required maxlength="30" name="telefone" inputmode="tel"></label><label>CNPJ <small>(opcional)</small><input maxlength="30" name="cnpj" inputmode="numeric"></label><button class="gf-cta" type="submit"><span><b>Quero falar com a equipe</b><small>Interesse sujeito à análise</small></span><span class="gf-arrow">→</span></button></form></section></main>
<footer class="gf-footer"><span>&copy; <?= date('Y') ?> GuinchaFácil</span><a href="<?= $e($bp) ?>/">Página inicial</a></footer></body></html>
