<?php
$bp = defined('BASE_PATH') ? BASE_PATH : '';
$e = static fn(string $v): string => htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
$flash = $flash ?? null;
$resultado = ($_GET['resultado'] ?? '') === '1' && !empty($cotacao) && (int)($cotacao['expira_em'] ?? 0) > time();

$forceTowDraft = is_array($forceTowDraft ?? null) ? $forceTowDraft : null;
$draftLocalizacao = (string)($forceTowDraft['localizacao'] ?? '');
$draftNumeroOrigem = (string)($forceTowDraft['numero_origem'] ?? '');
$draftLatOrigem = isset($forceTowDraft['lat_origem']) ? (string)$forceTowDraft['lat_origem'] : '';
$draftLngOrigem = isset($forceTowDraft['lng_origem']) ? (string)$forceTowDraft['lng_origem'] : '';
$draftCategoria = (string)($forceTowDraft['categoria'] ?? 'popular');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<?php require __DIR__ . '/../components/marketing_tracking.php'; ?>
<title>Cota&ccedil;&atilde;o de guincho e assist&ecirc;ncia veicular &mdash; GuinchaF&aacute;cil</title>
<meta name="description" content="Informe sua localiza&ccedil;&atilde;o e receba uma cota&ccedil;&atilde;o de guincho ou assist&ecirc;ncia veicular antes do cadastro.">
<link rel="canonical" href="https://guinchafacil.com.br/pre-cotacao">
<meta property="og:type" content="website">
<meta property="og:locale" content="pt_BR">
<meta property="og:title" content="Cota&ccedil;&atilde;o de guincho e assist&ecirc;ncia veicular">
<meta property="og:description" content="Veja sua cota&ccedil;&atilde;o antes de criar sua conta ou pagar.">
<meta property="og:url" content="https://guinchafacil.com.br/pre-cotacao">
<link rel="icon" href="<?= $e($bp) ?>/public/assets/img/favicon-32.png">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/vendor/fontawesome/css/all.min.css">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/vendor/leaflet/leaflet.css">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-pre-cotacao.css?v=20260812-3">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-landing.css?v=20260922-cities-menu">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-pre-cotacao-map.css?v=20260924-1">
<style>.address-fields{display:grid;grid-template-columns:minmax(0,1fr) 120px;gap:8px;position:relative}.address-number-label{display:block;font-size:.74rem;font-weight:700;color:#55705b;margin:0 0 4px}.regional-map-panel{margin-top:12px;padding:12px;border:1px solid #cfe3d3;border-radius:14px;background:#f7fbf7}.regional-map-panel[hidden]{display:none}.regional-map-head{display:flex;justify-content:space-between;gap:12px;font-size:.82rem;margin-bottom:8px}.regional-map-head span{color:#607066}.regional-map{height:280px;border-radius:10px;overflow:hidden}.funnel-navigation{display:flex;gap:8px;align-items:center}@media(max-width:520px){.address-fields{grid-template-columns:minmax(0,1fr) 94px}.regional-map-head{display:block}.regional-map{height:240px}.funnel-navigation{flex-wrap:wrap}.funnel-navigation .btn-main{flex-basis:100%}}</style>
<script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?> src="<?= $e($bp) ?>/public/assets/vendor/leaflet/leaflet.js"></script>
<script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?> src="<?= $e($bp) ?>/public/assets/js/public-quote-result.js"></script>
<style>.origin-map-composition{position:relative}.origin-map-composition:has(#originMapPanel:not([hidden]))>.col-12:first-child{position:absolute;z-index:999;top:26px;right:26px;width:min(390px,calc(100% - 52px));padding:14px;border-radius:14px;background:rgba(255,255,255,.97);box-shadow:0 5px 16px rgba(20,80,35,.16)}@media(max-width:520px){.origin-map-composition:has(#originMapPanel:not([hidden]))>.col-12:first-child{position:relative;top:auto;right:auto;width:auto;margin-top:10px;padding:0;background:transparent;box-shadow:none}}</style>
<style>
body{margin:0;background:#f4f8f5;color:#142018;font-family:system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:820px;margin:auto;padding:28px 18px 60px}.brand{color:#142018;text-decoration:none;font-weight:800;font-size:1.15rem}.brand strong{color:#2fb34a}.card{margin-top:34px;border:1px solid #d4e6d8;border-radius:22px;background:#fff;box-shadow:0 18px 50px rgba(20,80,35,.1);padding:28px}.eyebrow{color:#248f3a;font-size:.75rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.title{font-size:clamp(2rem,5vw,3.4rem);line-height:1.05;font-weight:850;letter-spacing:-.04em}.muted{color:#607066}.label{font-weight:650;font-size:.86rem;color:#405247}.form-control,.form-select{min-height:48px;border-color:#cfe3d3}.form-control:focus,.form-select:focus{border-color:#2fb34a;box-shadow:0 0 0 3px rgba(47,179,74,.15)}.btn-main{min-height:52px;border:0;border-radius:12px;background:#2fb34a;color:#fff;font-weight:800}.btn-main:hover{background:#248f3a;color:#fff}.quote{border:1px solid #b9dfc0;background:#edf8ef;border-radius:16px;padding:20px}.quote strong{font-size:2rem;color:#176d2c}.trust{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.trust span{padding:7px 10px;border-radius:999px;background:#f4f8f5;color:#55705b;font-size:.75rem}.back{color:#55705b;text-decoration:none;font-size:.9rem}
</style><style>.input-group{position:relative}.public-address-suggestions{position:absolute;z-index:20;top:calc(100% + 4px);left:0;right:0;background:#fff;border:1px solid #cfe3d3;border-radius:10px;box-shadow:0 10px 24px rgba(20,80,35,.14);overflow:hidden}.public-address-suggestions[hidden]{display:none}.public-address-suggestion{display:block;width:100%;border:0;border-bottom:1px solid #edf3ee;background:#fff;color:#25382b;text-align:left;padding:11px 13px;font-size:.88rem}.public-address-suggestion:last-child{border-bottom:0}.public-address-suggestion:hover,.public-address-suggestion:focus{background:#edf8ef;outline:0}</style></head><body><main class="wrap">
<header class="gf-nav"><a class="gf-brand" href="<?= $e($bp) ?>/"><img src="<?= $e($bp) ?>/public/assets/img/logo-48.png" alt="GuinchaF&aacute;cil" width="40" height="40"><span>Guincha<strong>F&aacute;cil</strong></span></a><nav aria-label="Navega&ccedil;&atilde;o principal"><a href="<?= $e($bp) ?>/#como-funciona">Como funciona</a><details class="gf-cities-menu"><summary>Cidades</summary><div class="gf-cities-dropdown"><span class="gf-cities-title">Atendimento por cidade</span><?php foreach (array_slice($cidadesSeo ?? [], 0, 20) as $cidadeSeo): ?><a href="<?= $e($bp) ?>/guincho/<?= $e((string)$cidadeSeo['slug']) ?>"><?= $e((string)$cidadeSeo['nome']) ?><?= !empty($cidadeSeo['uf']) ? ' - ' . $e(strtoupper((string)$cidadeSeo['uf'])) : '' ?></a><?php endforeach; ?><a class="gf-cities-all" href="<?= $e($bp) ?>/guincho">Ver todas as cidades</a></div></details><a href="<?= $e($bp) ?>/#parceiros">Seja parceiro</a><a class="gf-login" href="<?= $e($bp) ?>/login">Entrar</a></nav></header>
<section class="card" aria-labelledby="title">
<?php if (!$resultado): ?>
<p class="eyebrow">Sem cadastro nesta etapa</p><h1 id="title" class="title">Veja sua cota&ccedil;&atilde;o antes de criar sua conta.</h1>
<p class="muted">Informe os dados essenciais. Mostraremos as condi&ccedil;&otilde;es antes de voc&ecirc; decidir. Nada ser&aacute; cobrado agora.</p>
<?php if (!empty($flash)): ?><div class="alert alert-danger"><?= htmlspecialchars((string)($flash['message'] ?? ''), ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<form method="post" action="<?= $e($bp) ?>/pre-cotacao" class="row g-3" data-marketing-event="generate_lead">
<input type="hidden" name="csrf_token" value="<?= $e((string)($csrf_token ?? '')) ?>">
<div class="origin-map-composition"><div class="col-12"><label class="label" for="localizacao">Onde est&aacute; o ve&iacute;culo?</label><div class="address-fields"><div><input class="form-control" id="localizacao" name="localizacao" maxlength="220" placeholder="Rua, bairro e cidade" autocomplete="street-address" value="<?= $e($draftLocalizacao) ?>"></div><div><label class="address-number-label" for="numero_origem">N&uacute;mero</label><input class="form-control" id="numero_origem" name="numero_origem" maxlength="20" inputmode="numeric" placeholder="Ex.: 280" autocomplete="address-line2" required value="<?= $e($draftNumeroOrigem) ?>"></div></div><button class="btn btn-outline-success mt-2" id="btnGps" type="button">Usar minha localiza&ccedil;&atilde;o</button><small class="muted d-block mt-1" id="gpsStatus">Digite a rua e o n&uacute;mero. Se houver endere&ccedil;os iguais, escolha a cidade correta.</small></div>
<input type="hidden" id="lat_origem" name="lat_origem"><input type="hidden" id="lng_origem" name="lng_origem"><div id="originMapPanel" class="regional-map-panel" hidden><div class="regional-map-head"><strong>Confirme o ponto no mapa</strong><span id="mapAccuracyStatus">Arraste o pin até o local exato.</span></div><div id="originMap" class="regional-map" aria-label="Mapa regional para ajustar a localização"></div><small id="pinAddressStatus" class="muted">O endereço será atualizado a partir do pin. Se o número for estimado, você poderá revisá-lo.</small></div></div>
<div class="col-12" id="situacaoStage"><fieldset class="choice-fieldset"><legend class="label">O que aconteceu?</legend><input type="hidden" id="tipo_problema" name="tipo_problema" value="outro"><div class="choice-grid choice-grid-help">
<?php $ajudas = [['outro','fa-comments','Me orientem','Não sei qual caminho escolher.'],['mecanica','fa-user-cog','Resolver no local','Quero uma avaliação onde estou.'],['colisao','fa-truck-pickup','Levar o carro','Preciso de uma oficina ou destino.'],['pneu','fa-screwdriver-wrench','Outro problema','Vou explicar o que aconteceu.']]; foreach($ajudas as $i=>$a): ?><button type="button" class="choice-card<?= $i===0?' is-selected':'' ?>" data-choice-group="tipo_problema" data-choice-value="<?= $e($a[0]) ?>" aria-pressed="<?= $i===0?'true':'false' ?>"><i class="fas <?= $e($a[1]) ?>" aria-hidden="true"></i><strong><?= $a[2] ?></strong><small><?= $a[3] ?></small></button><?php endforeach; ?></div></fieldset></div>
<div class="col-12" id="vehicleStage"><fieldset class="choice-fieldset"><legend class="label">Qual &eacute; o tipo de ve&iacute;culo?</legend><input type="hidden" id="categoria" name="categoria" value="popular"><div class="choice-grid choice-grid-vehicle">
<?php $veiculos = [['popular','fa-car','Carro','Ve&iacute;culo de passeio comum.'],['moto','fa-motorcycle','Moto','Motocicleta ou scooter.'],['suv','fa-car-side','SUV','Ve&iacute;culo alto ou utilit&aacute;rio esportivo.'],['caminhonete','fa-truck-pickup','Caminhonete','Picape ou ve&iacute;culo de carga leve.'],['eletrico','fa-charging-station','El&eacute;trico','Ve&iacute;culo 100% el&eacute;trico.']]; foreach($veiculos as $i=>$v): ?><button type="button" class="choice-card<?= $i===0?' is-selected':'' ?>" data-choice-group="categoria" data-choice-value="<?= $e($v[0]) ?>" aria-pressed="<?= $i===0?'true':'false' ?>"><i class="fas <?= $e($v[1]) ?>" aria-hidden="true"></i><strong><?= $v[2] ?></strong><small><?= $v[3] ?></small></button><?php endforeach; ?></div></fieldset></div>
<div class="col-12 d-none" id="destinoBox"><label class="label" for="destino">Para onde deve levar o ve&iacute;culo?</label><div class="address-fields"><div><input class="form-control" id="destino" name="destino" maxlength="220" placeholder="Rua, bairro e cidade" autocomplete="street-address"></div><div><label class="address-number-label" for="numero_destino">N&uacute;mero</label><input class="form-control" id="numero_destino" name="numero_destino" maxlength="20" inputmode="numeric" placeholder="Ex.: 247" autocomplete="address-line2"><input type="hidden" id="lat_destino" name="lat_destino"><input type="hidden" id="lng_destino" name="lng_destino"></div></div><small class="muted">Digite o endere&ccedil;o e o n&uacute;mero; depois escolha a cidade sugerida para calcular a rota.</small></div>
<div class="col-12 funnel-navigation"><button class="btn btn-outline-secondary" id="btnSituacaoVoltar" type="button">Voltar</button><button class="btn btn-success" id="btnSituacaoAvancar" type="button">Avan&ccedil;ar</button><button class="btn-main flex-grow-1" id="btnCotacao" type="submit">Ver minha cota&ccedil;&atilde;o</button></div></form>
<?php else: ?>
<p class="eyebrow">Sua cota&ccedil;&atilde;o est&aacute; pronta</p><h1 id="title" class="title">Confira o valor antes de se cadastrar.</h1>
<div class="quote mt-4"><span class="muted"><?= htmlspecialchars((string)($cotacao['service_code'] ?? 'TOW_CAR'), ENT_QUOTES, 'UTF-8') ?> · <?= number_format((float)$cotacao['distancia_km'], 1, ',', '.') ?> km</span><br><strong>R$ <?= number_format((float)$cotacao['valor'], 2, ',', '.') ?></strong><p class="muted mb-0 mt-2">Calculada pelas regras vigentes da plataforma. V&aacute;lida por 15 minutos; o valor ser&aacute; revalidado antes do pagamento.</p></div>
<?php if (isset($cotacao['lat_origem'], $cotacao['lng_origem'], $cotacao['lat_destino'], $cotacao['lng_destino']) && $cotacao['lat_destino'] !== null && $cotacao['lng_destino'] !== null): ?>
<section class="quote-route-card mt-4" aria-labelledby="quote-route-title">
    <div class="quote-route-head"><div><span class="eyebrow">Trajeto estimado</span><h2 id="quote-route-title">Veja o caminho do reboque</h2></div><span id="quoteRouteStatus" class="muted">Calculando rota...</span></div>
    <div id="publicQuoteMap" class="public-quote-map" data-lat-origin="<?= $e((string)$cotacao['lat_origem']) ?>" data-lng-origin="<?= $e((string)$cotacao['lng_origem']) ?>" data-lat-destination="<?= $e((string)$cotacao['lat_destino']) ?>" data-lng-destination="<?= $e((string)$cotacao['lng_destino']) ?>" data-route-base="<?= $e($bp . '/api/routing/osrm') ?>"></div>
    <p class="muted small mb-0 mt-2">A rota exibida é uma estimativa para explicar a distância usada na cotação.</p>
</section>
<?php endif; ?>
<p class="muted mt-4">Nada foi cobrado e nenhum pedido foi criado. Para proteger seus dados e acompanhar o atendimento, crie sua conta quando decidir continuar.</p>
<form method="post" action="<?= $e($bp) ?>/pre-cotacao/aceitar" data-marketing-event="accept_quote"><input type="hidden" name="csrf_token" value="<?= $e((string)($csrf_token ?? '')) ?>"><button class="btn-main w-100" type="submit">Aceitar e criar cadastro</button></form>
<a class="back d-block text-center mt-3" href="<?= $e($bp) ?>/registro/cliente?retorno=%2Fcliente%2Fpedido%2Fnovo">Ir direto para o cadastro</a>
<a class="back d-block text-center mt-3" href="<?= $e($bp) ?>/pre-cotacao">Voltar e revisar os dados</a>
<?php endif; ?></section></main><script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?> src="<?= $e($bp) ?>/public/assets/js/public-pre-cotacao.js"></script><script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?> src="<?= $e($bp) ?>/public/assets/js/public-pre-cotacao-form.js"></script><script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?>><?php if ($prefillLat !== null && $prefillLng !== null): ?>document.addEventListener('DOMContentLoaded',function(){var lat=document.getElementById('lat_origem'),lng=document.getElementById('lng_origem'),status=document.getElementById('gpsStatus');if(lat&&lng){lat.value=<?= json_encode($prefillLat) ?>;lng.value=<?= json_encode($prefillLng) ?>;}if(status)status.textContent='LocalizaÃ§Ã£o aproximada da regiÃ£o selecionada. Confirme o ponto exato pelo GPS ou pelo endereÃ§o.';});<?php endif; ?><?php if ($forceTowDraft): ?>document.addEventListener('DOMContentLoaded',function(){var tipo=document.getElementById('tipo_problema'),categoria=document.getElementById('categoria'),lat=document.getElementById('lat_origem'),lng=document.getElementById('lng_origem'),status=document.getElementById('gpsStatus');if(tipo)tipo.value='colisao';if(categoria)categoria.value=<?= json_encode($draftCategoria) ?>;if(lat)lat.value=<?= json_encode($draftLatOrigem) ?>;if(lng)lng.value=<?= json_encode($draftLngOrigem) ?>;if(status)status.textContent='Informe agora para onde o veiculo deve ser levado para calcular o reboque.';document.dispatchEvent(new Event('prequote:type-change'));document.dispatchEvent(new Event('prequote:go-destination'));});<?php endif; ?></script></body></html>
<?php include __DIR__ . '/../components/modelo_atendimento.php'; ?>
