<?php
$bp = defined('BASE_PATH') ? BASE_PATH : '';
$e = static fn(string $v): string => htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
$flash = $flash ?? null;
$resultado = ($_GET['resultado'] ?? '') === '1' && !empty($cotacao) && (int)($cotacao['expira_em'] ?? 0) > time();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<?php require __DIR__ . '/../components/marketing_tracking.php'; ?>
<title>Cota&ccedil;&atilde;o de guincho e assist&ecirc;ncia veicular &mdash; GuinchaF&aacute;cil</title>
<meta name="description" content="Informe sua localiza&ccedil;&atilde;o e receba uma cota&ccedil;&atilde;o de guincho ou assist&ecirc;ncia veicular antes do cadastro.">
<link rel="canonical" href="https://guinchafacil.com.br/pre-cotacao">
<meta property="og:type" content="website">
<meta property="og:locale" content="pt_BR">
<meta property="og:title" content="Cota&ccedil;&atilde;o de guincho e assist&ecirc;ncia veicular">
<meta property="og:description" content="Veja sua cota&ccedil;&atilde;o antes de criar sua conta ou pagar.">
<meta property="og:url" content="https://guinchafacil.com.br/pre-cotacao">
<link rel="icon" href="<?= $e($bp) ?>/public/assets/img/favicon-32.png">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/vendor/fontawesome/css/all.min.css">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-pre-cotacao.css?v=20260812-3">
<link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-landing.css">
<style>
body{margin:0;background:#f4f8f5;color:#142018;font-family:system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:820px;margin:auto;padding:28px 18px 60px}.brand{color:#142018;text-decoration:none;font-weight:800;font-size:1.15rem}.brand strong{color:#2fb34a}.card{margin-top:34px;border:1px solid #d4e6d8;border-radius:22px;background:#fff;box-shadow:0 18px 50px rgba(20,80,35,.1);padding:28px}.eyebrow{color:#248f3a;font-size:.75rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.title{font-size:clamp(2rem,5vw,3.4rem);line-height:1.05;font-weight:850;letter-spacing:-.04em}.muted{color:#607066}.label{font-weight:650;font-size:.86rem;color:#405247}.form-control,.form-select{min-height:48px;border-color:#cfe3d3}.form-control:focus,.form-select:focus{border-color:#2fb34a;box-shadow:0 0 0 3px rgba(47,179,74,.15)}.btn-main{min-height:52px;border:0;border-radius:12px;background:#2fb34a;color:#fff;font-weight:800}.btn-main:hover{background:#248f3a;color:#fff}.quote{border:1px solid #b9dfc0;background:#edf8ef;border-radius:16px;padding:20px}.quote strong{font-size:2rem;color:#176d2c}.trust{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.trust span{padding:7px 10px;border-radius:999px;background:#f4f8f5;color:#55705b;font-size:.75rem}.back{color:#55705b;text-decoration:none;font-size:.9rem}
</style><style>.input-group{position:relative}.public-address-suggestions{position:absolute;z-index:20;top:calc(100% + 4px);left:0;right:0;background:#fff;border:1px solid #cfe3d3;border-radius:10px;box-shadow:0 10px 24px rgba(20,80,35,.14);overflow:hidden}.public-address-suggestions[hidden]{display:none}.public-address-suggestion{display:block;width:100%;border:0;border-bottom:1px solid #edf3ee;background:#fff;color:#25382b;text-align:left;padding:11px 13px;font-size:.88rem}.public-address-suggestion:last-child{border-bottom:0}.public-address-suggestion:hover,.public-address-suggestion:focus{background:#edf8ef;outline:0}</style></head><body><main class="wrap">
<header class="gf-nav"><a class="gf-brand" href="<?= $e($bp) ?>/"><img src="<?= $e($bp) ?>/public/assets/img/logo-48.png" alt="GuinchaF&aacute;cil" width="40" height="40"><span>Guincha<strong>F&aacute;cil</strong></span></a><nav aria-label="Navega&ccedil;&atilde;o principal"><a href="<?= $e($bp) ?>/#como-funciona">Como funciona</a><a href="<?= $e($bp) ?>/#parceiros">Seja parceiro</a><a class="gf-login" href="<?= $e($bp) ?>/login">Entrar</a></nav></header>
<section class="card" aria-labelledby="title">
<?php if (!$resultado): ?>
<p class="eyebrow">Sem cadastro nesta etapa</p><h1 id="title" class="title">Veja sua cota&ccedil;&atilde;o antes de criar sua conta.</h1>
<p class="muted">Informe os dados essenciais. Mostraremos as condi&ccedil;&otilde;es antes de voc&ecirc; decidir. Nada ser&aacute; cobrado agora.</p>
<?php if (!empty($flash)): ?><div class="alert alert-danger"><?= htmlspecialchars((string)($flash['message'] ?? ''), ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<form method="post" action="<?= $e($bp) ?>/pre-cotacao" class="row g-3" data-marketing-event="generate_lead">
<input type="hidden" name="csrf_token" value="<?= $e((string)($csrf_token ?? '')) ?>">
<div class="col-12"><label class="label" for="localizacao">Onde est&aacute; o ve&iacute;culo?</label><div class="input-group"><input class="form-control" id="localizacao" name="localizacao" maxlength="220" placeholder="Use o bot&atilde;o ou informe um ponto de refer&ecirc;ncia"><button class="btn btn-outline-success" id="btnGps" type="button">Usar minha localiza&ccedil;&atilde;o</button></div><small class="muted" id="gpsStatus">A localiza&ccedil;&atilde;o precisa ser confirmada para calcular a cota&ccedil;&atilde;o.</small></div>
<input type="hidden" id="lat_origem" name="lat_origem"><input type="hidden" id="lng_origem" name="lng_origem">
<div class="col-12"><fieldset class="choice-fieldset"><legend class="label">Que tipo de ajuda voc&ecirc; precisa?</legend><input type="hidden" id="tipo_problema" name="tipo_problema" value="outro"><div class="choice-grid choice-grid-help">
<?php $ajudas = [['outro','fa-circle-question','Ainda n&atilde;o sei','N&atilde;o tenho certeza do problema.'],['bateria','fa-car-battery','Bateria','O carro n&atilde;o liga ou precisa de partida auxiliar.'],['pneu','fa-circle-notch','Pneu furado','Precisa trocar ou reparar um pneu.'],['combustivel','fa-gas-pump','Pane seca','Ficou sem combust&iacute;vel no caminho.'],['eletrica','fa-bolt','Pane el&eacute;trica','Falha em luzes, fios ou sistema el&eacute;trico.'],['mecanica','fa-screwdriver-wrench','Pane mec&acirc;nica','O carro parou por uma falha mec&acirc;nica.'],['colisao','fa-car-burst','Colis&atilde;o / reboque','Precisa remover o ve&iacute;culo do local.']]; foreach($ajudas as $i=>$a): ?><button type="button" class="choice-card<?= $i===0?' is-selected':'' ?>" data-choice-group="tipo_problema" data-choice-value="<?= $e($a[0]) ?>" aria-pressed="<?= $i===0?'true':'false' ?>"><i class="fas <?= $e($a[1]) ?>" aria-hidden="true"></i><strong><?= $a[2] ?></strong><small><?= $a[3] ?></small></button><?php endforeach; ?></div></fieldset></div>
<div class="col-12"><fieldset class="choice-fieldset"><legend class="label">Qual &eacute; o tipo de ve&iacute;culo?</legend><input type="hidden" id="categoria" name="categoria" value="popular"><div class="choice-grid choice-grid-vehicle">
<?php $veiculos = [['popular','fa-car','Carro','Ve&iacute;culo de passeio comum.'],['moto','fa-motorcycle','Moto','Motocicleta ou scooter.'],['suv','fa-car-side','SUV','Ve&iacute;culo alto ou utilit&aacute;rio esportivo.'],['caminhonete','fa-truck-pickup','Caminhonete','Picape ou ve&iacute;culo de carga leve.'],['eletrico','fa-charging-station','El&eacute;trico','Ve&iacute;culo 100% el&eacute;trico.']]; foreach($veiculos as $i=>$v): ?><button type="button" class="choice-card<?= $i===0?' is-selected':'' ?>" data-choice-group="categoria" data-choice-value="<?= $e($v[0]) ?>" aria-pressed="<?= $i===0?'true':'false' ?>"><i class="fas <?= $e($v[1]) ?>" aria-hidden="true"></i><strong><?= $v[2] ?></strong><small><?= $v[3] ?></small></button><?php endforeach; ?></div></fieldset></div>
<div class="col-12 d-none" id="destinoBox"><label class="label" for="destino">Para onde o ve&iacute;culo deve ser levado?</label><input class="form-control" id="destino" name="destino" maxlength="220" placeholder="Informe o endere&ccedil;o de destino"><input type="hidden" id="lat_destino" name="lat_destino"><input type="hidden" id="lng_destino" name="lng_destino"><small class="muted">Para colis&atilde;o ou reboque, precisamos do destino para calcular a rota.</small></div>
<div class="col-12"><button class="btn-main w-100" type="submit">Ver minha cota&ccedil;&atilde;o</button></div></form>
<div class="trust"><span>Sem cobran&ccedil;a nesta etapa</span><span>Pre&ccedil;o explicado antes da confirma&ccedil;&atilde;o</span><span>Voc&ecirc; decide se quer continuar</span></div>
<?php else: ?>
<p class="eyebrow">Sua cota&ccedil;&atilde;o est&aacute; pronta</p><h1 id="title" class="title">Confira o valor antes de se cadastrar.</h1>
<div class="quote mt-4"><span class="muted"><?= htmlspecialchars((string)($cotacao['service_code'] ?? 'TOW_CAR'), ENT_QUOTES, 'UTF-8') ?> · <?= number_format((float)$cotacao['distancia_km'], 1, ',', '.') ?> km</span><br><strong>R$ <?= number_format((float)$cotacao['valor'], 2, ',', '.') ?></strong><p class="muted mb-0 mt-2">Calculada pelas regras vigentes da plataforma. V&aacute;lida por 15 minutos; o valor ser&aacute; revalidado antes do pagamento.</p></div>
<p class="muted mt-4">Nada foi cobrado e nenhum pedido foi criado. Para proteger seus dados e acompanhar o atendimento, crie sua conta quando decidir continuar.</p>
<form method="post" action="<?= $e($bp) ?>/pre-cotacao/aceitar" data-marketing-event="accept_quote"><input type="hidden" name="csrf_token" value="<?= $e((string)($csrf_token ?? '')) ?>"><button class="btn-main w-100" type="submit">Aceitar e criar cadastro</button></form>
<a class="back d-block text-center mt-3" href="<?= $e($bp) ?>/registro/cliente?retorno=%2Fcliente%2Fpedido%2Fnovo">Ir direto para o cadastro</a>
<a class="back d-block text-center mt-3" href="<?= $e($bp) ?>/pre-cotacao">Voltar e revisar os dados</a>
<?php endif; ?></section></main><script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?> src="<?= $e($bp) ?>/public/assets/js/public-pre-cotacao.js"></script><script<?php echo function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : ''; ?> src="<?= $e($bp) ?>/public/assets/js/public-pre-cotacao-form.js"></script></body></html>
