<?php
$bp = defined('BASE_PATH') ? BASE_PATH : '';
$e = static fn(string $v): string => htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
$canonical = 'https://guinchafacil.com.br/parceiros';
$description = 'Conecte seu negócio à GuinchaFácil: receba oportunidades qualificadas, tenha apoio operacional e amplie resultados com parceria transparente.';
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Programa de Parceiros | GuinchaFácil</title><meta name="description" content="<?= $e($description) ?>"><link rel="canonical" href="<?= $canonical ?>"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="GuinchaFácil"><meta property="og:title" content="Programa de Parceiros | GuinchaFácil"><meta property="og:description" content="<?= $e($description) ?>"><meta property="og:image" content="https://guinchafacil.com.br/public/assets/img/landing/roadside-help.jpg"><meta property="og:url" content="<?= $canonical ?>"><link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/tokens.css"><link rel="stylesheet" href="<?= $e($bp) ?>/public/assets/css/pages/public-landing.css"><script<?= function_exists('csp_script_nonce_attr') ? csp_script_nonce_attr() : '' ?> type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'Organization','name'=>'GuinchaFácil','url'=>'https://guinchafacil.com.br/','logo'=>'https://guinchafacil.com.br/public/assets/img/logo-48.png','description'=>$description], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><style>
.gf-cta--guincho{background:linear-gradient(135deg,#041a09 0%,#0a3d1a 45%,#2fb34a 100%)!important;color:#fff!important;box-shadow:0 6px 18px rgba(47,179,74,.28)!important;border:0!important}
.gf-cta--guincho .gf-arrow{color:#fff!important}
.gf-cta--oficina{background:linear-gradient(135deg,#1a0a00 0%,#6d3b08 45%,#f0a83b 100%)!important;color:#fff!important;box-shadow:0 6px 18px rgba(240,168,59,.30)!important;border:0!important}
.gf-cta--oficina .gf-arrow{color:#fff!important}
</style></head><body class="gf-landing"><header class="gf-nav"><a class="gf-brand" href="<?= $e($bp) ?>/"><img src="<?= $e($bp) ?>/public/assets/img/logo-48.png" alt="Logotipo GuinchaFácil" width="40" height="40"><span>Guincha<strong>Fácil</strong></span></a><nav aria-label="Navegação principal"><a href="<?= $e($bp) ?>/">Precisa de socorro?</a><a class="gf-login" href="<?= $e($bp) ?>/login">Entrar</a></nav></header>
<main><section class="gf-hero" aria-labelledby="partner-title"><div><p class="gf-eyebrow">Programa de parceiros</p><h1 id="partner-title">Seu negócio move pessoas. <em>Nós ajudamos a mover oportunidades.</em></h1><p class="gf-lead">A GuinchaFácil aproxima motoristas de empresas preparadas para atender. Escolha como quer participar da nossa rede.</p></div><div class="gf-card"><div class="gf-card-head"><span class="gf-dot"></span><b>Escolha seu perfil</b></div><div class="gf-location"><span>↗</span><div><small>Atendimento móvel</small><b>Guincho parceiro</b></div></div><a class="gf-cta gf-cta--guincho" href="<?= $e($bp) ?>/parceiros/guinchos"><span><b>Seja um Guincho Parceiro</b><small>Receba chamados compatíveis</small></span><span class="gf-arrow">→</span></a><div class="gf-location"><span>⌂</span><div><small>Reparos e manutenção</small><b>Oficina parceira</b></div></div><a class="gf-cta gf-cta--oficina" href="<?= $e($bp) ?>/parceiros/oficinas"><span><b>Seja uma Oficina Parceira</b><small>Ocupe horários disponíveis</small></span><span class="gf-arrow">→</span></a></div></section>
<section class="gf-trust" aria-label="Por que ser parceiro"><div><b>Oportunidades qualificadas</b><span>Demandas encaminhadas para perfis e regiões compatíveis.</span></div><div><b>Repasse organizado</b><span>O painel acompanha atendimento, reputação e fluxo de PIX.</span></div><div><b>Sem exclusividade</b><span>Você mantém sua carteira e escolhe sua disponibilidade.</span></div></section>
<section class="gf-section" aria-labelledby="summary-title"><p class="gf-eyebrow">Como funciona</p><h2 id="summary-title">Da oportunidade ao repasse, sem letra miúda</h2><div class="gf-process"><article><i>01</i><h3>Escolha seu perfil</h3><p>Guincho ou oficina: cada página explica cenários, pagamentos e operação.</p></article><article><i>02</i><h3>Envie o interesse</h3><p>O cadastro não cria conta automaticamente; a equipe avalia o parceiro.</p></article><article><i>03</i><h3>Atenda e acompanhe</h3><p>Receba notificações, atualize status e consulte repasses no painel.</p></article></div></section>
<section class="gf-partner"><div><p class="gf-eyebrow">Escolha a operação</p><h2>Quer entender pagamentos, cenários reais e exemplos de ganhos?</h2><p>Veja os detalhes financeiros, operacionais e técnicos do perfil que combina com o seu negócio.</p></div><a href="<?= $e($bp) ?>/parceiros/guinchos">Ver páginas de parceiros →</a></section></main><footer class="gf-footer"><span>&copy; <?= date('Y') ?> GuinchaFácil</span><div><a href="<?= $e($bp) ?>/">Página inicial</a><a href="<?= $e($bp) ?>/pre-cotacao">Fazer cotação</a></div></footer></body></html>
