<?php
$bp = defined('BASE_PATH') ? BASE_PATH : '';
$csrfToken = $csrfToken ?? AuthService::gerarCsrfToken();
include __DIR__ . '/../layouts/header.php';
?>
<style>
.specialist-admin-form{--orange:#d88918;--orange-dark:#a85b08;--orange-bg:#21170b;--orange-surface:#2b2114;color:#fff;max-width:1100px;margin:0 auto;padding:28px}
.specialist-admin-form .card{background:var(--orange-bg);border:1px solid rgba(216,137,24,.28);border-radius:16px}.specialist-admin-form .form-control,.specialist-admin-form .form-select{background:var(--orange-surface)!important;border-color:rgba(216,137,24,.35)!important;color:#fff!important}.specialist-admin-form .form-label{color:#f3d29b;font-weight:600}.specialist-admin-form h1{font-weight:800}.specialist-admin-form .section-title{color:#f0a83b;font-size:.78rem;letter-spacing:1px;text-transform:uppercase;font-weight:800;border-bottom:1px solid rgba(216,137,24,.3);padding-bottom:8px;margin:24px 0 14px}.specialist-admin-form .service{display:block;border:1px solid rgba(216,137,24,.35);border-radius:10px;padding:12px;color:#ffe4b0;height:100%}.specialist-admin-form .btn-orange{background:linear-gradient(135deg,#edaa35,#b9670c);border:0;color:#1b1004;font-weight:800}.specialist-admin-form .hint{color:#c7a977;font-size:.88rem}
</style>
<main class="specialist-admin-form">
  <div class="d-flex justify-content-between align-items-start mb-4"><div><span class="text-uppercase" style="color:#f0a83b;letter-spacing:1px;font-size:.75rem;font-weight:800">Admin · Rede de atendimento</span><h1 class="mt-2">Cadastrar especialista</h1><p class="hint">Cadastre o profissional diretamente no painel administrativo.</p></div><a class="btn btn-outline-warning" href="<?= htmlspecialchars($bp) ?>/admin/especialistas"><i class="fas fa-arrow-left me-1"></i>Voltar</a></div>
  <div class="card p-4"><form method="post" action="<?= htmlspecialchars($bp) ?>/registro/especialista"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="admin" value="1">
    <div class="section-title"><i class="fas fa-toolbox me-2"></i>Capacidades técnicas</div><div class="row g-2"><?php foreach(['LOCKOUT'=>'Chaveiro','ELECTRICAL_DIAG'=>'Avaliação elétrica','BATTERY_JUMP'=>'Partida auxiliar','TIRE_CHANGE'=>'Troca de pneu','FUEL_DELIVERY'=>'Entrega de combustível'] as $codigo=>$nome): ?><div class="col-md-4"><label class="service"><input type="checkbox" name="servicos[]" value="<?= $codigo ?>" class="form-check-input me-2"><strong><?= $nome ?></strong><small class="d-block hint">Serviço disponível para despacho</small></label></div><?php endforeach; ?></div>
    <div class="section-title"><i class="fas fa-user me-2"></i>Dados pessoais</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Nome completo</label><input name="nome" class="form-control" required></div><div class="col-md-6"><label class="form-label">Nome profissional</label><input name="nome_profissional" class="form-control"></div><div class="col-md-4"><label class="form-label">E-mail</label><input type="email" name="email" class="form-control" required></div><div class="col-md-4"><label class="form-label">Telefone</label><input name="telefone" class="form-control" required></div><div class="col-md-4"><label class="form-label">CPF</label><input name="cpf" class="form-control" required></div><div class="col-md-6"><label class="form-label">Senha provisória</label><input type="password" name="senha" minlength="8" class="form-control" required></div><div class="col-md-6"><label class="form-label">Confirmar senha</label><input type="password" name="confirmar_senha" minlength="8" class="form-control" required></div></div>
    <div class="section-title"><i class="fas fa-location-dot me-2"></i>Área de atendimento</div><div class="row g-3"><div class="col-md-3"><label class="form-label">CEP</label><input name="cep" class="form-control" required></div><div class="col-md-6"><label class="form-label">Logradouro</label><input name="logradouro" class="form-control" required></div><div class="col-md-3"><label class="form-label">Número</label><input name="numero" class="form-control" required></div><div class="col-md-5"><label class="form-label">Bairro</label><input name="bairro" class="form-control" required></div><div class="col-md-5"><label class="form-label">Cidade</label><input name="cidade" class="form-control" required></div><div class="col-md-2"><label class="form-label">UF</label><input name="estado" maxlength="2" class="form-control" required></div></div>
    <div class="section-title"><i class="fas fa-wallet me-2"></i>Repasse e operação</div><div class="row g-3"><div class="col-md-5"><label class="form-label">Chave Pix</label><input name="chave_pix" class="form-control" required></div><div class="col-md-3"><label class="form-label">Tipo Pix</label><select name="chave_pix_tipo" class="form-select"><option value="cpf">CPF</option><option value="cnpj">CNPJ</option><option value="email">E-mail</option><option value="telefone">Telefone</option><option value="aleatoria">Aleatória</option></select></div><div class="col-md-4"><label class="form-label">Raio de atendimento (km)</label><input type="number" name="raio_atendimento_km" value="10" min="1" max="100" class="form-control" required></div><div class="col-12"><label class="form-label">Experiência / observações</label><textarea name="bio" rows="3" class="form-control"></textarea></div></div>
    <button class="btn btn-orange btn-lg mt-4"><i class="fas fa-user-plus me-2"></i>Cadastrar especialista</button>
  </form></div>
</main>
<?php include __DIR__ . '/../layouts/footer.php'; ?>
