CREATE TABLE IF NOT EXISTS comunicados (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(120) NOT NULL,
    subtitulo VARCHAR(220) NULL,
    etiqueta VARCHAR(40) NULL,
    publico ENUM('cliente','guincho','ambos') NOT NULL,
    placement VARCHAR(64) NOT NULL,
    formato ENUM('wide','card') NOT NULL DEFAULT 'wide',
    tema ENUM('auto','light','dark','success','warning','info') NOT NULL DEFAULT 'auto',
    imagem_desktop VARCHAR(255) NOT NULL,
    imagem_mobile VARCHAR(255) NULL,
    imagem_alt VARCHAR(180) NOT NULL DEFAULT '',
    object_position_x TINYINT UNSIGNED NOT NULL DEFAULT 50,
    object_position_y TINYINT UNSIGNED NOT NULL DEFAULT 50,
    cta_label VARCHAR(40) NULL,
    cta_url VARCHAR(500) NULL,
    cta_target ENUM('self','blank') NOT NULL DEFAULT 'self',
    status ENUM('rascunho','publicado','pausado','arquivado') NOT NULL DEFAULT 'rascunho',
    prioridade SMALLINT NOT NULL DEFAULT 100,
    inicio_em DATETIME NULL,
    fim_em DATETIME NULL,
    duracao_slide_seg TINYINT UNSIGNED NOT NULL DEFAULT 8,
    frequencia ENUM('sempre','sessao','dia') NOT NULL DEFAULT 'sempre',
    dismissivel TINYINT(1) NOT NULL DEFAULT 0,
    dismiss_ttl_horas SMALLINT UNSIGNED NOT NULL DEFAULT 24,
    criado_por INT NULL,
    atualizado_por INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_comunicados_publicacao (status, publico, placement, inicio_em, fim_em),
    KEY idx_comunicados_prioridade (placement, prioridade, id),
    KEY idx_comunicados_criado_por (criado_por)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comunicado_metricas_diarias (
    comunicado_id BIGINT UNSIGNED NOT NULL,
    data DATE NOT NULL,
    perfil ENUM('cliente','guincho') NOT NULL,
    impressoes INT UNSIGNED NOT NULL DEFAULT 0,
    cliques INT UNSIGNED NOT NULL DEFAULT 0,
    fechamentos INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (comunicado_id, data, perfil),
    KEY idx_comunicado_metricas_data (data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
