CREATE TABLE IF NOT EXISTS pedido_localizacoes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pedido_id INT NOT NULL,
    guincho_id INT NOT NULL,
    usuario_id INT NOT NULL,
    fase VARCHAR(32) NOT NULL,
    sequence_number INT NOT NULL,
    client_point_id VARCHAR(80) NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    accuracy_m DECIMAL(10,2) NULL,
    speed_mps DECIMAL(10,2) NULL,
    heading_deg DECIMAL(10,2) NULL,
    device_timestamp BIGINT NULL,
    server_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_point_id BIGINT UNSIGNED NULL,
    distance_raw_m DECIMAL(12,2) NOT NULL DEFAULT 0,
    distance_validated_m DECIMAL(12,2) NOT NULL DEFAULT 0,
    distance_accumulated_m DECIMAL(12,2) NOT NULL DEFAULT 0,
    elapsed_ms BIGINT NULL,
    calculated_speed_kmh DECIMAL(10,2) NULL,
    street_name VARCHAR(255) NULL,
    street_source VARCHAR(64) NULL,
    match_confidence DECIMAL(5,2) NULL,
    is_valid TINYINT(1) NOT NULL DEFAULT 1,
    rejection_code VARCHAR(32) NULL,
    hash_previous CHAR(64) NULL,
    hash_current CHAR(64) NULL,
    request_id VARCHAR(64) NULL,
    run_id VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pedido_client_point (pedido_id, client_point_id),
    UNIQUE KEY uk_pedido_sequence (pedido_id, sequence_number),
    KEY idx_pedido_ts (pedido_id, server_timestamp),
    KEY idx_guincho_ts (guincho_id, server_timestamp),
    KEY idx_pedido_fase_valid (pedido_id, fase, is_valid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pedido_percurso_resumos (
    pedido_id INT NOT NULL,
    fase VARCHAR(32) NOT NULL,
    total_points INT NOT NULL DEFAULT 0,
    valid_points INT NOT NULL DEFAULT 0,
    rejected_points INT NOT NULL DEFAULT 0,
    started_at DATETIME NULL,
    last_point_at DATETIME NULL,
    duration_seconds INT NOT NULL DEFAULT 0,
    distance_raw_m DECIMAL(12,2) NOT NULL DEFAULT 0,
    distance_validated_m DECIMAL(12,2) NOT NULL DEFAULT 0,
    max_gap_seconds INT NOT NULL DEFAULT 0,
    max_speed_kmh DECIMAL(10,2) NOT NULL DEFAULT 0,
    tracking_quality VARCHAR(32) NOT NULL DEFAULT 'unknown',
    last_street VARCHAR(255) NULL,
    last_latitude DECIMAL(10,8) NULL,
    last_longitude DECIMAL(11,8) NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (pedido_id, fase)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
