CREATE TABLE IF NOT EXISTS pedido_evidencias (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pedido_id INT NOT NULL,
    guincho_id INT NOT NULL,
    tipo ENUM('coleta','entrega') NOT NULL,
    status ENUM('pending','accepted','rejected') NOT NULL DEFAULT 'accepted',
    nonce_token VARCHAR(255) NOT NULL,
    nonce_expires_at DATETIME NOT NULL,
    point_id BIGINT UNSIGNED NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    accuracy_m DECIMAL(10,2) NULL,
    device_timestamp BIGINT NULL,
    server_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NOT NULL,
    metadata_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pedido_tipo (pedido_id, tipo, status),
    KEY idx_point_id (point_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
