<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(403); exit; }
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../src/Services/Logger.php'; require_once __DIR__.'/../src/Services/EspecialistaAtendimentoService.php'; require_once __DIR__.'/../src/Services/EspecialistaProofOfRoadService.php';
$run='qa-canonical-'.date('YmdHis');
function stepLog(string $step, array $ctx=[]): void { global $run; Logger::log(Logger::LEVEL_INFO,'qa_canonical_specialista',$step,'qa_e2e',$step,$ctx+['run_id'=>$run]); fwrite(STDOUT,"[QA][$step] ".json_encode($ctx,JSON_UNESCAPED_UNICODE).PHP_EOL); }
try {
 $p=getPDO(); stepLog('inicio',['run_id'=>$run]);
 $q=$p->prepare('SELECT id FROM usuarios WHERE email=?'); $q->execute(['pw_socorro_cliente@guinchafacil.com']); $cliente=(int)$q->fetchColumn();
 $q=$p->prepare('SELECT id FROM especialistas WHERE usuario_id=(SELECT id FROM usuarios WHERE email=?)'); $q->execute(['especialista.qa.canonico@guinchafacil.com']); $esp=(int)$q->fetchColumn();
 if (!$esp) { $q=$p->prepare("SELECT id FROM usuarios WHERE email=?"); $q->execute(['pw_socorro_especialista@guinchafacil.com']); $eu=(int)$q->fetchColumn(); $p->prepare("INSERT INTO especialistas (usuario_id,nome_profissional,cpf_cnpj,documento_tipo,chave_pix,chave_pix_tipo,aprovado,disponivel,lat_atual,lng_atual) VALUES (?,?,?,?,?,'aleatoria',1,1,-22.90,-43.10)")->execute([$eu,'Especialista QA Canônico','10987654303','CPF','qa-canonico-'.$eu]); $esp=(int)$p->lastInsertId(); }
 $q=$p->prepare('SELECT id FROM veiculos WHERE usuario_id=? LIMIT 1'); $q->execute([$cliente]); $veiculo=(int)$q->fetchColumn(); $servico=(int)$p->query('SELECT id FROM servicos_especialista ORDER BY id LIMIT 1')->fetchColumn();
 if(!$cliente||!$esp||!$veiculo||!$servico) throw new RuntimeException('IDs QA ausentes'); stepLog('ids',['cliente'=>$cliente,'especialista'=>$esp,'veiculo'=>$veiculo,'servico'=>$servico]);
 $p->prepare('UPDATE especialistas SET aprovado=1,disponivel=1,lat_atual=-22.90,lng_atual=-43.10 WHERE id=?')->execute([$esp]);
 $p->prepare("INSERT INTO incidentes (cliente_id,veiculo_id,tipo_problema,descricao_problema,lat_origem,lng_origem,endereco_origem,status) VALUES (?,?,?,?,?,?,?,'especialista_designado')")->execute([$cliente,$veiculo,'bateria','QA canônico '.$run,-22.90,-43.10,'Local QA']); $inc=(int)$p->lastInsertId(); stepLog('incidente_criado',['incidente_id'=>$inc]);
 $p->prepare("INSERT INTO atendimentos_especialista (incidente_id,especialista_id,servico_solicitado_id,status,provider_amount,platform_amount,customer_amount,ofertado_em,expiracao_oferta) VALUES (?,?,?,'ofertado',80,20,100,NOW(),DATE_ADD(NOW(),INTERVAL 5 MINUTE))")->execute([$inc,$esp,$servico]); $at=(int)$p->lastInsertId(); stepLog('atendimento_ofertado',['atendimento_id'=>$at]);
 $p->prepare("INSERT INTO financeiro_lancamentos (incidente_id,tipo,referencia_tipo,referencia_id,valor,status) VALUES (?,'repasse_especialista','atendimento_especialista',?,80,'pendente')")->execute([$inc,$at]); stepLog('repasse_pendente',['atendimento_id'=>$at,'valor'=>80]);
 EspecialistaAtendimentoService::aceitar($at,$esp); stepLog('aceite',['atendimento_id'=>$at]); EspecialistaAtendimentoService::transicionar($at,$esp,'a_caminho',['aceito']); stepLog('a_caminho',['atendimento_id'=>$at]);
 EspecialistaProofOfRoadService::registrarEvento($at,$esp,'gps',-22.90,-43.10,10); stepLog('gps_valido',['atendimento_id'=>$at]); EspecialistaAtendimentoService::transicionar($at,$esp,'no_local',['a_caminho']); stepLog('chegada',['atendimento_id'=>$at]); EspecialistaAtendimentoService::transicionar($at,$esp,'em_diagnostico',['no_local']); stepLog('diagnostico_iniciado',['atendimento_id'=>$at]); EspecialistaAtendimentoService::transicionar($at,$esp,'necessita_reboque',['em_diagnostico']); require_once __DIR__ . '/../src/Services/TowEscalationService.php'; TowEscalationService::solicitar($inc,$cliente); stepLog('fallback_solicitado',['incidente_id'=>$inc]);
 $q=$p->prepare("SELECT status FROM financeiro_lancamentos WHERE incidente_id=? AND referencia_id=? AND tipo='repasse_especialista'");$q->execute([$inc,$at]);$repasse=(string)$q->fetchColumn(); stepLog('repasse_final',['status'=>$repasse]); if($repasse!=='confirmado') throw new RuntimeException('Repasse não confirmado no fallback'); echo json_encode(['ok'=>true,'run_id'=>$run,'incidente_id'=>$inc,'atendimento_id'=>$at,'repasse'=>$repasse],JSON_UNESCAPED_UNICODE).PHP_EOL;
} catch(Throwable $e) { Logger::exception('qa_canonical_specialista','run','qa_e2e',$e,['run_id'=>$run]); fwrite(STDERR,"[QA][ERRO] {$e->getMessage()}\n{$e->getTraceAsString()}\n"); exit(1); }
